spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/jan_price_checker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

mybatis:
  mapper-locations: classpath:mapper/*.xml
